#!/usr/bin/env ruby

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'pry'
require 'guac'
require 'guac/cli'

Signal.trap('INT') do
  warn "\n#{caller.join("\n")}: interrupted" if Guac.debug?

  warn 'CMD+C interrupted'
  warn "\nWELL EXCUUUUUUUUSE ME. NO 👏 GUAC 👏 FOR 👏 YOU 👏".red

  exit 1
end

begin
  Guac::CLI.start
rescue Guac::Commands::Error => e
  puts 'ERROR: '.red + e.message
  exit 1
rescue Guac::CLI::Error => e
  puts 'ERROR: '.red + e.message
  exit 1
end
